version: '3.7'

networks:
  app: {}

#volumes:
#  mysqldata: {}

services:
  app:
    build:
      context: .
      dockerfile: docker/shell/Dockerfile
    image: changeme-typescript-starter
    hostname: changeme-typescript-starter
    working_dir: /app
    networks:
      - app
#    depends_on:
#      - db
#      - db-testing
#      - phpmyadmin
    volumes:
      - ./:/app
      - ~/.npmrc:/root/.npmrc
      - ~/.npmrc:/home/node/.npmrc
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
    ports:
      - 4200:4200
      - 8080:8080
    environment:
      SSH_AUTH_SOCK: "${SSH_AUTH_SOCK}"
#      APP_DB_HOST: db
#      APP_TEST_DB_HOST: db-testing
#      APP_DB_USER: app
#      APP_DB_PASS: app
#      APP_DB_NAME: app
#      APP_TEST_DB_NAME: app-testing
    stdin_open: true
    tty: true

#  db:
#    image: mysql:5.7
#    restart: always
#    hostname: db
#    networks:
#      - app
#    ports:
#      - 3306:3306
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    environment:
#      MYSQL_DATABASE: app
#      MYSQL_USER: app
#      MYSQL_PASSWORD: app
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - mysqldata:/var/lib/mysql
#
#  # The testing DB service has no volume. That is by design. [wh]
#  db-testing:
#    image: mysql:5.7
#    restart: always
#    hostname: db-testing
#    networks:
#      - app
#    ports:
#      - 3307:3306
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    environment:
#      MYSQL_DATABASE: app-testing
#      MYSQL_USER: app
#      MYSQL_PASSWORD: app
#      MYSQL_ROOT_PASSWORD: root
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    hostname: phpmyadmin
#    container_name: phpmyadmin
#    networks:
#      - app
#    ports:
#      - 8079:80
#    environment:
#      PMA_HOSTS: >-
#        db,
#        db-testing,
#      PMA_USER: app
#      PMA_PASSWORD: app
